version: '3'
services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: postgres-0
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash-0:12201"
    ports:
      - "5433:5432"
    restart: unless-stopped
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch-0
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - default
    restart: always
  kibana:
    image: kibana:8.13.0
    container_name: kibana-0
    environment:
      - node.name=kibana
      - cluster.name=docker-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch-0:9200
    ports:
      - "5601:5601"
    networks:
      - default
    depends_on:
      - elasticsearch
    restart: always
  logstash:
    image: logstash:8.13.0
    container_name: logstash-0
    restart: always
    volumes:
      - ./logstash/:/home/user/IdeaProjects/ms-personnel-modules/logstash/
    command: logstash -f /home/user/IdeaProjects/ms-personnel-modules/logstash/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9600:9600"
    networks:
      - default
    depends_on:
      - elasticsearch


volumes:
  esdata1:
    driver: local
networks:
  default:
    driver: bridge
