version: '3'
services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: postgres-0
    environment:
      POSTGRES_DB: persondb
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

#  app:
#    build: ./ms-person
#    container_name: ms-person
#    ports:
#      - "8080:8080"
#    environment:
#      POSTGRES_HOST: db
#    depends_on:
#      - db
#    restart: always

#  nginx:
#    image: nginx:1.25.2-alpine
#    container_name: nginx
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "8081:8080"
#    depends_on:
#      - app
