version: '4'
services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: postgres-0
    environment:
      POSTGRES_DB: persondb
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
  cache:
    image: "redis"
    ports:
      - "6397:6397"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL