spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?reWriteBatchedInserts=true
    username: pg
    password: 123
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        jdbc:
          batch_size: 50
        generate_statistics: false
        order_inserts: true
        order_updates: true

schedulerService:
  showPersonCount:
    intervalInMillis: 10000

queueListener:
  persistQueueData:
    intervalInMillis: 5000